name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -p 10022 -i private_key ${USER_NAME}@${HOST_NAME} 'cd /home/altecseng/altecs.jp/public_html/Sample/ && git pull origin master'
